# LICENSE HEADER MANAGED BY add-license-header
#
# Copyright 2026 NTNU/SINTEF/Statnett SF
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#



model_data_path='sample_datasets/n44/model_data.json'

[topics]
"application.status"="application.status"
"pmudata"="pmudata"
"pmu.coords"="pmu.coords"
"modeestimation"="modeestimation"
"alarms"="alarms"
"voltage.stability.index"="voltage.stability.index"
"islanding"="islanding"
"grid.events"="grid.events"
"model.data"="model.data"
"application.commands"="application.commands"


[streaming]
type="nqkafka"
bootstrap_servers="localhost:40000"


[geo_data]
countries=["Norway", "Sweden", "Denmark", "Finland"]
line_data_path='sample_datasets/n44/sld_geo.dxf'

[sld_data]
line_data_path='sample_datasets/n44/sld.dxf'

[database]
type="sqlite"
file_path="sample_datasets/n44/grid_database.db"

[single_line_diagrams]
[single_line_diagrams.geo]
countries=["Norway", "Sweden", "Denmark", "Finland"]
aspect_ratio=2
data_path='sample_datasets/n44/sld_geo.dxf'
geographic=true

[single_line_diagrams.other]
data_path='sample_datasets/n44/sld.dxf'

