# # include=['model_measurement_map.toml']
include=['startup_apps.toml']
model_data_path='data/model_data.json'


[pmus]
ip='localhost'
port=50000

[pdc]
ip='localhost'
port=50000
id=1


# ['graphics']
# background_color=[255, 255, 255]
# gl_mode='translucent'

[topics]
"application.status"="application.status"
"application.commands"="application.commands"
"pmudata"="pmudata"
"pmu.coords"="pmu.coords"
"modeestimation"="modeestimation"
"voltage.stability.index"="voltage.stability.index"
"alarms"="alarms"
"islanding"="islanding"
"grid.events"="grid.events"
"model.data"="model.data"

[streaming]
# type="kafka"
# bootstrap_servers="localhost:9094"
type="nqkafka"
bootstrap_servers="localhost:40000"
# type="mqtt"
# hostname="localhost"
# port=1883



# [database]
# type="file"
# file_path='data/model_data.json'
[database]
type="sqlite"
file_path="data/grid_database.db"

[geo_data]
countries=["Norway", "Sweden", "Denmark", "Finland"]
line_data_path='data/sld_geo.dxf'

[sld_data]
line_data_path='data/sld.dxf'
